export const CREATE_RECIPE = 'CREATE_RECIPE';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE_DETAIL = 'GET_RECIPE_DETAIL';
export const GET_RECIPES_TYPES = 'GET_RECIPES_TYPES';
export const ORDER_RECIPES_BY_NAME = 'ORDER_RECIPES_BY_NAME';
export const FILTER_CREATED = 'FILTER_CREATED';
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';     